name: www.beste-party-musik.de
description: Hochzeiten, Geburtstage, Firmenevents und Ü30 / Ü40 / Ü50 Partys. Seit 35 Jahren DJ und Veranstalter im Raum Bonn, Köln und Oberberg. 
baseurl: '/'

url: "http://beste-party-musik.de"

paginate: 10

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag